### ISSUE TITLE
support nested keys

### ISSUE THREAD

**Issue by conorhastings** [kentcdodds/match-sorter#1]
from the roadmap - https://github.com/kentcdodds/match-sorter/blob/master/other/ROADMAP.md

Notes:
* - don't worry about odd key names like `name.first` - https://twitter.com/kentcdodds/status/769921548232732672

Happy to hear any ideas on implementation details.

**Comment by kentcdodds** [comment]
I'm sure there's a module that'll do it. Right now the build isn't setup to work with multiple files, but if you want to find a (small) module that can do it and make a pull request for that, then I'll figure out the build stuff.

**Comment by conorhastings** [comment]
@kentcdodds can we do something simple like this - https://github.com/conorhastings/match-sorter/commit/45722aabfd06a3589a554eb8c79443c47d084c2e

**Comment by kentcdodds** [comment]
Perfect! I can merge that right away!

**Comment by kentcdodds** [comment]
Oh also remove that item from the roadmap too
