### ISSUE TITLE
Base sort should still be applied if the search string is empty

### ISSUE THREAD

**Issue by RebeccaStevens** [kentcdodds/match-sorter#100]
- `match-sorter` version: 4.2.0
- `node` version: 14.8.0
- `npm` (or `yarn`) version: 6.14.7 (or 1.21.1 :stuck_out_tongue:)

Relevant code or config

```js
import matchSorter from 'match-sorter'

const list = ['hi', 'hey', 'hello', 'sup', 'yo']

const sorted = matchSorter(list, '')
```

What you did:

```js
console.log(sorted);
```

What happened:

The list was returned unsorted.

Problem description:

As no search string was supplied, all items should have the same ranking, therefore the base sort should be applied as the tie-breaker. i.e. The list should be sorted but it's not.

Suggested solution:

If the search string is empty, apply the base sort instead of just returning the list unsorted.

Additional Note:

I stole the "Relevant code" from the Usage section of the Read Me. When I did, I noticed that it's slightly out of date now as the base sort is not be applied to the output.
`matchSorter(list, 'h') // ['hi', 'hey', 'hello']` should be `matchSorter(list, 'h') // [ 'hello', 'hey', 'hi' ]`

**Comment by kentcdodds** [comment]
Thanks for the issue Rebecca. I agree with you. Would you be willing to make a pull request to add this functionality (and fix the README too)?

**Comment by RebeccaStevens** [comment]
Made the PR :)
