### ISSUE TITLE
How to ignore caseRank while sorting?

### ISSUE THREAD

**Issue by mrceperka** [kentcdodds/match-sorter#103]
Hello :wave:,
I've got a question and could not find the solution on the internet, so I ask here.

- `match-sorter` version: 4.2.1
- `node` version: 12.18.4
- `npm` (or `yarn`) version: yarn 1.22.4

What you did: https://codesandbox.io/s/react-codesandbox-forked-t5tb4?file=/src/index.js
What happened: Items are sorted the way I do not expect/want.

Reproduction repository: see sandbox please

Problem description:
I want to sort items alphabetically, without additional case ranking. Case ranking causes unexpected (for me) sort. 

Suggested solution:
Maybe, there already is an option to avoid this. But i was unable to find it. It would be great, if i could "just" sort by value, without case ranking consideration.

Maybe something like this could be used: https://github.com/mrceperka/match-sorter/blob/match-sorter-possible-fix/src/index.js#L135

Thanks :pray:

**Comment by kentcdodds** [comment]
Hi @mrceperka,

Could you call `toLowerCase` on the input and the values using the "Property Callbacks" feature shown in the README?

```javascript
const list = [{name: 'Janice'}, {name: 'Fred'}, {name: 'George'}, {name: 'Jen'}]
const input = 'J'
matchSorter(list, input.toLowerCase(), {keys: [item => item.name.toLowerCase()]})
// [{name: 'Janice'}, {name: 'Jen'}]
```

**Comment by mrceperka** [comment]
I could and I will try but I am.afraid that it won't help. Because
lowercase of `-` is the same. And this character is causing caseRank
increase (bacause it will pick some casing I guess)

Will let you know tomorrow.

Thanks for reply.

**Comment by mrceperka** [comment]
@kentcdodds Sadly, did not work for me. Please, check this sandbox - https://codesandbox.io/s/react-codesandbox-forked-t5tb4?file=/src/index.js

**Comment by kentcdodds** [comment]
Ah, that's a bummer. I think I actually ran into this same problem yesterday: https://kifs.netlify.app/

Those should be sorted alphabetically by default, but the three with `'` show up first.

Hmmm.... I think it'd be even better if we could only consider alphabetical characters when matching case 🤔

Would you be willing to [add a failing test](https://github.com/kentcdodds/match-sorter/blob/418ada28e0cacc9c504ed07a415ebe0d8caf4564/src/__tests__/index.js#L461) for this?

**Comment by mrceperka** [comment]
@kentcdodds Sure thing, please, check https://github.com/kentcdodds/match-sorter/pull/106

> I think it'd be even better if we could only consider alphabetical characters when matching case
- I would rather have this as an option
- I would leave sorting to `JS.sort()` and `baseSort` if provided

**Comment by kentcdodds** [comment]
I normally don't like logical options like this, but I don't think there's a reasonable alternative. Would you like to implement your suggestion?

Thanks!

**Comment by mrceperka** [comment]
@kentcdodds Yes, I will implement it. I will update existing PR asap.

**Comment by mrceperka** [comment]
@kentcdodds bad news, sorting alphabetically be default breaks **12** tests. I am afraid that it can't be done by default without bumping major version...

**Comment by kentcdodds** [comment]
I figured. I don't mind bumping the major version, bit I'm curious how they break and whether the breakage is desirable.

**Comment by mrceperka** [comment]
It would be best if you could clone PR branch, uncomment that test case and run `npm test`... Or I can paste log/screenshot here.
