### ISSUE TITLE
Property callback or nested keys possible?

### ISSUE THREAD

**Issue by tannerlinsley** [kentcdodds/match-sorter#11]
I'm working with some objects that need to be searched using a sub-property of the object.  Most other solutions provide a callback of sorts to locate said properties or support `Object.array[]` string syntax (similar to lodash's `_.get(object, 'path')` method).

Thoughts?

**Comment by tannerlinsley** [comment]
Just saw this: https://github.com/kentcdodds/match-sorter/issues/1.  Nice!

**Comment by kentcdodds** [comment]
I have thought about making it possible to provide a property callback. Perhaps any item in the `keys` could be a function. Would you like to make that happen? The changes would be fairly minimal and limited to [here](https://github.com/kentcdodds/match-sorter/blob/1cb4be579ed0ceab7060d91debbf45b41e023596/src/index.js#L181-L187) with tests added around [here](https://github.com/kentcdodds/match-sorter/blob/1cb4be579ed0ceab7060d91debbf45b41e023596/src/index.test.js#L132) and docs could just be another example [here](https://github.com/kentcdodds/match-sorter/blob/1cb4be579ed0ceab7060d91debbf45b41e023596/README.md#usage).

**Comment by tannerlinsley** [comment]
Yeah I could make that happen

**Comment by kentcdodds** [comment]
This is now supported. Thanks @clauderic!

**Comment by tannerlinsley** [comment]
👏
