### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/match-sorter#12]
The project's features have grown passed the simple code example and I think we should probably add more complete and organized documentation, at least for the properties in the `options` object. **Anyone wanna take this on?** It'd basically amount to taking code examples from [here](https://github.com/kentcdodds/match-sorter/blob/1cb4be579ed0ceab7060d91debbf45b41e023596/README.md#usage), and putting them in a (new) `Options` section (probably below `Usage`) with subsections for each property with some prose explaining what it's for and a small code example (taken from the `Usage` section).

**Comment by rogeliog** [comment]
I'm happy to help here :)

**Comment by kentcdodds** [comment]
Wonderful! Let me know if you have questions. Make sure to follow the [CONTRIBUTING.md](https://github.com/kentcdodds/match-sorter/blob/master/CONTRIBUTING.md)
