### ISSUE TITLE
 error TS7016: Could not find a declaration file for module 'match-sorter'. '...../node_modules/match-sorter/dist/match-sorter.cjs.js'

### ISSUE THREAD

**Issue by ethanstrominger** [kentcdodds/match-sorter#138]
- `match-sorter` version: 4.1.0
- `node` version: 16.13

Relevant code or config

```javascript
import matchSorter from 'match-sorter';
import { matchSorter } from 'match-sorter';
import * as matchSorter from 'match-sorter';
```

What you did:
I added each of those lines to a typescrpt file.  

What happened:
When I run tsc, tsc reports error  error TS7016: Could not find a declaration file for module 'match-sorter'. '/.../node_modules/match-sorter/dist/match-sorter.cjs.js'

I tried both with and without @types/match-sorter installed.

Reproduction repository:
https://github.com/ethanstrominger/match-sorter-issue

Problem description:
See above

Suggested solution:
Correct @types/match-sorter

**Comment by kentcdodds** [comment]
Try reinstalling? Because that type definition file is definitely there: https://unpkg.com/browse/match-sorter@6.3.1/dist/match-sorter.cjs.d.ts

**Comment by ethanstrominger** [comment]
I did - I get the same error.

**Comment by ethanstrominger** [comment]
This is a listing of what is in @types/match-sorter:
`node_modules/@types/match-sorter/node_modules/match-sorter/dist $ ls -1
```
index.d.ts
match-sorter.cjs.d.ts
match-sorter.cjs.js
match-sorter.esm.d.ts
match-sorter.esm.js
match-sorter.umd.d.ts
match-sorter.umd.js
match-sorter.umd.js.map
match-sorter.umd.min.d.ts
match-sorter.umd.min.js
match-sorter.umd.min.js.map`
```

**Comment by ethanstrominger** [comment]
I made the error go away by creating a file in my src directory called match-sorter.d.ts with the line `declare module 'match-sorter';`
