### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by rogeliog** [kentcdodds/match-sorter#14]
The [demo](https://jsbin.com/vewoka/edit?js,output) throws the following error, which happens because the imported `matchSorter.rankings` is undefined.

<img width="550" alt="screen shot 2016-08-31 at 9 42 55 am" src="https://cloud.githubusercontent.com/assets/574806/18137931/5b228a3c-6f5f-11e6-9fb7-a1f349dfa23d.png">

The demo is using `https://npmcdn.com/match-sorter@^1.1.0` which needs to be bumped to the latest version and moved from `npmcdn` to `unpkg`.

**Comment by kentcdodds** [comment]
Thanks for finding that! It should be working now :)

**Comment by kentcdodds** [comment]
Ooooh, actually it's not... Looks like something's wrong with the export of the `rankings` object... Probably an issue that happened with #9

**Comment by kentcdodds** [comment]
@rogeliog, I've filed a PR that should fix these issues. Let me know what you think.
