### ISSUE TITLE
feat: return matched pos

### ISSUE THREAD

**Issue by Akimotorakiyu** [kentcdodds/match-sorter#144]
use case:
list: [{name:'hello'},{name:'other'}]
input: e
matched: [{name:'hello'},{name:'other'}]

when should highlight the matched char, we need pos of matched char to do that

h e🍺 llo
oth e🍺 r
thanks!

**Comment by kentcdodds** [comment]
Unfortunately this would require a significant overhaul of the library that I'm not sure we should do. I believe there are other libraries that do this. I'm not sure what they are. Sorry, but I don't think we'll support this here.
