### ISSUE TITLE
Defer the assignment of `matchSorter.rankings`

### ISSUE THREAD

**Issue by mochaaP** [kentcdodds/match-sorter#147]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `match-sorter@6.3.2` for the project I'm working on.

Rollup got confused here and rewrote `matchSorter` to an anonymous function assigning to a variable, making an ReferenceError.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/match-sorter/dist/match-sorter.esm.js b/node_modules/match-sorter/dist/match-sorter.esm.js
index 19a6b97..6dffe8c 100644
--- a/node_modules/match-sorter/dist/match-sorter.esm.js
+++ b/node_modules/match-sorter/dist/match-sorter.esm.js
@@ -11,7 +11,6 @@ var rankings = {
   MATCHES: 1,
   NO_MATCH: 0
 };
-matchSorter.rankings = rankings;
 var defaultBaseSortFn = function defaultBaseSortFn(a, b) {
   return String(a.rankedValue).localeCompare(String(b.rankedValue));
 };
@@ -58,6 +57,7 @@ function matchSorter(items, value, options) {
     return matches;
   }
 }
+matchSorter.rankings = rankings;
 
 /**
  * Gets the highest ranking for value for the given item based on its values for the given keys
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by kentcdodds** [comment]
That change is fine for me. Could you make a PR?
