### ISSUE TITLE
Add Support for ImmutableJS

### ISSUE THREAD

**Issue by ericadamski** [kentcdodds/match-sorter#29]
Add support for [ImmutableJS](https://facebook.github.io/immutable-js/) data structures.

Allow:
- A shallow `Immutable.List` to be passed. (Supports native javascript types inside the `List`)
    eg.
    ```javascript
     match(new List(['a', 'b', 'c'], 'a', /*options*/);
     or
     match(new List([
          { name: 'a' },
          { name: 'b' },
     ]), 'a', { key: 'name' });
    ```
- A deep `Immutable.List` to be passed. (Supports nested `Immutable.Map`s over native javascript `Objects`)
    eg
    ```javascript
     match(new List([
          new Map({ name: 'a' }),
          new Map({ name: 'b' })
     ], 'a', { key: 'name' });
    ```

All the same functionality that exists with native javascript arrays and objects will be available using List and Maps including nested keys and arrays of values.

**Comment by kentcdodds** [comment]
Hi @ericadamski. I believe that this is already supported... If you're experiencing issues, could you create a reproduction of your issues in [codesandbox](https://codesandbox.io/s/new)? And suggest a solution. Remember that match-sorter has support for "Property Callbacks" in the [key property](https://github.com/kentcdodds/match-sorter#keys-string) which pretty much allows you to do anything.

**Comment by ericadamski** [comment]
Ha! It is hilarious that I missed that entire feature even while reproducing the code :/

**Comment by ericadamski** [comment]
https://github.com/kentcdodds/match-sorter/issues/29#issuecomment-331466705
