### ISSUE TITLE
Search through array of objects within list of objects?

### ISSUE THREAD

**Issue by markwoon** [kentcdodds/match-sorter#30]
- `match-sorter` version: 2.0.2
- `node` version: 8.5.0
- `npm` (or `yarn`) version: 1.1.0

```javascript
const list = [
  { data: [ { a: '1' }, {a: '2'} ] }
  { data: [ { a: '2' }, {a: '4'} ] }
]

matchSorter(list, {keys: 'data.a'});
```

Is there a way to search an array of objects where what I'm actually interested in is the array of objects inside?  In the example above, I'm interested in searching through the `a` property of the `data` list.

**Comment by kentcdodds** [comment]
Hi @markwoon! You can use `keys: Function`. It's called "Property Callbacks" in the docs:

````
Property Callbacks: Alternatively, you may also pass in a callback function that resolves the value of the key(s) you wish to match on. This is especially useful when interfacing with libraries such as Immutable.js

```js
const list = [
  {name: 'Janice'},
  {name: 'Fred'},
  {name: 'George'},
  {name: 'Jen'},
]
matchSorter(list, 'j', {keys: [(item) => item.name]})
// [{name: 'Janice'}, {name: 'Jen'}]
```
````

**Comment by kentcdodds** [comment]
Let me know if that doesn't solve your problem :)
