### ISSUE TITLE
Null Checks for resolving nested key

### ISSUE THREAD

**Issue by cliewpaypal** [kentcdodds/match-sorter#31]
- `match-sorter` version: 2.0.2
- `node` version: v4.7.3
- `npm` (or `yarn`) version: 3.10.10

Relevant code or config

```javascript
const matchSorterFilterMethodFlattened = (filter, rows, column) => {
  return matchSorter(rows, filter.value, { keys: 'thing.nestedThing' });
};
```

Sample Table data:
```
[
  {
    "name": "row1",
    "thing": {
      "nestedThing:": "nestedValue"
    }
  },
  {
    "name": "row2",
    "thing": null
  }
]
```

What you did:

What happened:

Reproduction repository:

Problem description:
```
value = key.split('.').reduce(function (itemObj, nestedKey) {
return itemObj[nestedKey];
```

Suggested solution:
Do a null check here (and maybe resolve search result as false for empty nested objects?) 
```
value = key.split('.').reduce(function (itemObj, nestedKey) {
return itemObj[nestedKey];
```

**Comment by kentcdodds** [comment]
Sounds great to me! Thanks @cliewpaypal! Would you like to [make a pull request](http://makeapullrequest.com) to make this happen?

**Comment by cliewpaypal** [comment]
placeholder PR:
https://github.com/kentcdodds/match-sorter/pull/32
