### ISSUE TITLE
match keys with array within list of objects

### ISSUE THREAD

**Issue by hozefaj** [kentcdodds/match-sorter#35]
- `match-sorter` version: `2.2.0`
- `node` version: `6.10.2`
- `npm` (or `yarn`) version: `npm 3.10.10`

I am looking to do some search from a list of objects. However, the objects themselves contain couple properties that are arrays.

```js
this.state = {
    searchedOffers: matchSorter(this.props.offers, this.props.searchTerm, {
    keys: ['content[0].merchant_name'],
    });
};

// offers: PropTypes.array,
// searchTerm: PropTypes.string
```
However this does not work. I am wondering how I can match against an array within the object.

**Comment by kentcdodds** [comment]
Try `content.0.merchant_name`

I don't think I want to support `[x]` property accessors in the keys strings because that would add a fair amount of code. I _would_ however accept a pull request to document this limitation. :)

**Comment by hozefaj** [comment]
@kentcdodds `content.0.merchant_name` works. Thanks 👍 

I will send PR updating docs with this use case :)

FYI, using this with a paypal app(https://www.paypal.com/deals)

**Comment by kentcdodds** [comment]
I figured! That's awesome 🎉
