### ISSUE TITLE
maintain order of original data if no search term is provided

### ISSUE THREAD

**Issue by hozefaj** [kentcdodds/match-sorter#39]
- `match-sorter` version: `2.2.0`
- `node` version: `v8.9.3`
- `npm` (or `yarn`) version:  `npm v5.7.1`

Relevant code or config
```javascript
segments = matchSorter(this.props.segments.list, searchTerm, {
  keys: ['id', 'code', 'description'],
});
```

What you did:
1. perform a search with proper value of `searchTerm`
2. empty `searchTerm` out. `matchSorter` modifies the order of the response, does not maintain the original order when no search term is entered.

Suggested solution:
I guess checking for [value](https://github.com/kentcdodds/match-sorter/blob/master/src/index.js#L42) before the actual search and sorting is performed. So if `searchTerm` is empty just return the input as is.

**Comment by kentcdodds** [comment]
So you're suggesting this change?

```diff
 function matchSorter(items, value, options = {}) {
+   if (!value) {
+     return  items
+   }
   const {keys, threshold = rankings.MATCHES} = options
   const matchedItems = items.reduce(reduceItemsToRanked, [])
   return matchedItems.sort(sortRankedItems).map(({item}) => item)
```

I think I'm good with that. Want to make a PR?

**Comment by hozefaj** [comment]
Yeah sure. Will do.
