### ISSUE TITLE
Inconsistent module resolution with typescript under node/web

### ISSUE THREAD

**Issue by yakirn** [kentcdodds/match-sorter#41]
- `match-sorter` version:2.2.1
- `node` version:8.2.1
- `npm` (or `yarn`) version:yarn 1.0.2/npm 5.8.0

What you did:
Basically trying to use match-sorter with typescript in browser and node.

What happened:

An error is thrown when trying to test a file that imports match-sorter.

Reproduction repository:

https://github.com/yakirn/matchsorter-ts

Problem description:
I used a very basic setup. create-react-app with typescript as described [here](https://github.com/Microsoft/TypeScript-React-Starter#create-our-new-project).
I added basic match-sorter code to `App.tsx`.
When running using `yarn start` a browser pops up and everything works as expected.
But when trying to test the component using `yarn test` an error is thrown:
Error: Uncaught [TypeError: match_sorter_1.default is not a function]

Suggested solution:
I'm no sure why, but `import matchSorter from 'match-sorter';` works in the browser but not in node.
while `import * as matchSorter from 'match-sorter';` works in node, but not in the browser.

I would love to help solve this issue, and later add types definition, but I guess there's a problem with the bundler of this project, and I can use some guidance.
Thanks!

**Comment by kentcdodds** [comment]
I'm guessing this is happening because node is resolving your require/import to the `package.json` `main` field and webpack is resolving your require/import to the `package.json` `module` field. These are slightly different to facilitate an improved experience for people using CommonJS and UMD. I'm planning on changing this, and that will be a breaking change which should have fairly minimal impact so hopefully I can get to it soon.

**Comment by yakirn** [comment]
Great, thanks! Will you accept a PR with TypeScript type definitions?

**Comment by kentcdodds** [comment]
Sure. Just know that I wont maintain it, so you'll have to stay on top of things :)

**Comment by kentcdodds** [comment]
Which shouldn't be too difficult considering this library doesn't change a whole lot.

**Comment by paulrimiru** [comment]
Hey, Is there any progress in this issue getting solved, I am facing the same problem

**Comment by kentcdodds** [comment]
I can probably get this fixed today.
