### ISSUE TITLE
Multiple priority sort Issue

### ISSUE THREAD

**Issue by mohak1990** [kentcdodds/match-sorter#42]
matchSorter(arr, "t", {keys: ["Name","Surname"]})

In this case if both Name and Surname has "t", still it returns an empty string.
It works if any one of the 2 cases are passed.
Expected:
The return array should be a sorted one having "t" in any of the 2 cases(or both, but giving sort priority "Name")

**Comment by ChrisRu** [comment]
According to the tests and a test I ran myself just now, this works fine.
[Test for key priority](https://github.com/kentcdodds/match-sorter/blob/4ab02aef5afc8ae4985b46737385a30a0e8f9a3c/src/__tests__/index.js#L96)

Maybe it would be nice to see the full code with the array supplied or perhaps a different example, to make sure?

**Comment by mohak1990** [comment]
Sorry, I missed quotes for each case. Thanks
