### ISSUE TITLE
Polyfill for IE11 - String.prototype.includes

### ISSUE THREAD

**Issue by luish** [kentcdodds/match-sorter#44]
match-sorter: 2.2.1
node: v6.11.3
npm: 5.6.0

We've been using this lib and it failed on Internet Explorer 11 because of the following line:

https://github.com/kentcdodds/match-sorter/blob/5f2c8092d4d9c31eabb9cb9ac8e74ad83a8a55d9/src/index.js#L190

> Object doesn’t support property or method ‘includes’

So I'm wondering if I could contribute to this repo by adding a polyfill such as these ones:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Polyfill
- https://github.com/mathiasbynens/String.prototype.includes

Thanks :)

**Comment by kentcdodds** [comment]
That'd be fine with me.
