### ISSUE TITLE
callback to allow for transformation of matched items whilst keeping original list

### ISSUE THREAD

**Issue by natehardy** [kentcdodds/match-sorter#49]
It would be nice to be able to return all items in the array with a transform function to allow for adding properties to the matched items but keeping the original list.

For example: If I wanted to return a list of the matched items with a visible key attached so allow for animation on the nodes that are not matched eg collapsing them from view.

**Comment by kentcdodds** [comment]
How about this:

```js
matchSorter(items.map(/* whatever */), ...etc)
```
