### ISSUE TITLE
Limit the results

### ISSUE THREAD

**Issue by brenoos** [kentcdodds/match-sorter#52]
Hello.

There's a way to limite the results? For example: I just want the 5 first matches, not the all matches.

Thanks

**Comment by kentcdodds** [comment]
Hi @brenoos :wave:

Use [Array.prototype.slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice). For example:

```js
const allResults = matchSorter(list, searchString)
const firstFiveResults = allResults.slice(0, 5)
```

Good luck!
