### ISSUE TITLE
Combine value selector function with min/maxRanking?

### ISSUE THREAD

**Issue by cmeeren** [kentcdodds/match-sorter#53]
I'm not a JS dev, I'm just trying to create bindings for this library for use in F# with Fable. Looking at the docs and the current master branch, it doesn't seem possible to use the value selector function along with `minRanking` and `maxRanking`. Is that intended?

With the value selector function, I am talking about this:

```f#
matchSorter(list, 'j', {keys: [item => item.name]})
```

It would be great if this could be combined with setting `minRanking` and `maxRanking`.

**Comment by kentcdodds** [comment]
Hi @cmeeren,

I'm not sure what you're hoping to accomplish by combining those though. Could you explain what you're trying to do and I'll do my best to help.

**Comment by ChrisRu** [comment]
You can pass an object inside the `keys` array. Here in you can set `minRanking` along with `key`.
See here an example of this: https://runkit.com/embed/5iynukr92n7k
Does this help?

**Comment by cmeeren** [comment]
Oh, it seems it's already possible, then! I'll try that when I get home. The [typings](https://www.npmjs.com/package/@types/match-sorter) did not surface this possibility.

**Comment by kentcdodds** [comment]
Perhaps the typings need to be fixed. Would you be willing to make a contribution for those?

**Comment by cmeeren** [comment]
I'd guess it's an easy fix, but I don't know TS and I don't know how much time I'd need to understand enough to make such a contribution. I'd be hard pressed to prioritize it at the moment. Are you involved in the typings in any way?

(For easy reference, [here's the typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/match-sorter/index.d.ts).)

**Comment by kentcdodds** [comment]
I'm not.

**Comment by cmeeren** [comment]
I can confirm that it does actually work, and that the bindings are incomplete. I've created an issue for the bindings [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32038). Thanks!

**Comment by kentcdodds** [comment]
Moving discussion to that issue.
