### ISSUE TITLE
Bug with Acronym?

### ISSUE THREAD

**Issue by cmeeren** [kentcdodds/match-sorter#54]
When setting `threshold` to `ACRONYM`, `"sa"` will match `"Afghanistan"`. Repro based on the demo: https://codesandbox.io/s/73yjqy23lj

I would expect `"Afghanistan"` to not be matched by `"sa"` for `ACRONYM`, only for `MATCHES` and `NO_MATCH`.

**Comment by cmeeren** [comment]
Additionally, `"sa"` will match `"Aland Islands"`, and `"as"` will match `"Australia"` and `"Austria"`.

**Comment by kentcdodds** [comment]
Interesting. I'm not sure what's up.

I'm afraid that I'm not actively using this package so I don't have any time to dedicate to figuring out what the issue is. If you do find what the problem is I welcome you to [make a pull request](http://makeapullrequest.com) to fix it.

**Comment by cmeeren** [comment]
Gotcha. Since I'm not a JS dev and also have very limited time, I'll leave this for someone else.

**Comment by sdbrannum** [comment]
I believe this issue is stemming from the use of `>=` in `reduceItemsToRanked()` paired with `getRanking()` found in `getClosenessRanking()` 

``` 
function getRanking(spread) {
    const matching = spread - stringToRank.length + 1;
    const ranking = rankings.MATCHES + 1 / matching
    return ranking
}
```

This function will, in certain cases as mentioned above, return 2 which when compared to the acronym threshold will return the item.

**Comment by kentcdodds** [comment]
Thanks Steven,

Any chance you could make a PR with a failing test first so I can see how this bug plays out in a practical scenario?

**Comment by kentcdodds** [comment]
Thanks to @sdbrannum for fixing this!

**Comment by kentcdodds** [comment]
@all-contributors please add @cmeeren for bugs
