### ISSUE TITLE
Escape period?

### ISSUE THREAD

**Issue by nathanforce** [kentcdodds/match-sorter#59]
* `match-sorter` version: 2.3.0
* `node` version: 
* `npm` (or `yarn`) version: 

Relevant code or config

```javascript
const placeholders = [{ searchTerms: [project!.slug, 'slug', 'project.slug'] }];

const matches = matchSorter(placeholders, 'project.slug', {
    keys: ['searchTerms'],
});

```

What you did: Searching for the string `"project.slug"` returns an empty result.

Problem description: I want to be able to search for the string `"project.slug"` and match the item in the placeholders array.

Suggested solution: ?

**Comment by kentcdodds** [comment]
Hmmm... Seems like a bug I think. Could you make a reproduction you and I (and anyone else) can look into?

**Comment by nathanforce** [comment]
Nevermind.  The bug was caused by another lib (the one providing my `searchTerm`) not allowing period.  Sorry for wasting your time!

HOT TAKE: match-sorter is your best lib

**Comment by kentcdodds** [comment]
I'm glad you like it!
