### ISSUE TITLE
Error with number filtering

### ISSUE THREAD

**Issue by samyan** [kentcdodds/match-sorter#65]
Hi. I have found possible bug when trying to filter an array with number type fields containing the same values

* `match-sorter` version: 3.5.1
* `node` version: 10.15.3
* `npm`  version: 6.9.0

**Code Example:**

```
let p = [{ name: 'samuel', likes: 0 }, { name: 'pedro', likes: 0 }];

const result = matchSorter(p, '0', {
	keys: ['name', 'likes'],
	threshold: rankings.WORD_STARTS_WITH
});

console.log(result);
```

**Error:**
`TypeError
aRankedItem.localeCompare is not a function`

[**Live Example**](https://codesandbox.io/s/match-sorter-bug-tx2iw)

**Problem:**
If I'm not mistaken, the problem is that the match-sorter try to call the function <localeCompare> of the String class from a variable of Number type. My solution was simply, when trying to compare, I cast the variable to String in any case.

**Possible Solution:**
```
function sortRankedItems(a, b) {
	var aFirst = -1;
	var bFirst = 1;
	var aRankedItem = a.rankedItem,
		aRank = a.rank,
		aKeyIndex = a.keyIndex;
	var bRankedItem = b.rankedItem,
		bRank = b.rank,
		bKeyIndex = b.keyIndex;

	if (aRank === bRank) {
		if (aKeyIndex === bKeyIndex) {
			return String(aRankedItem).localeCompare(bRankedItem);
		} else {
			return aKeyIndex < bKeyIndex ? aFirst : bFirst;
		}
	} else {
		return aRank > bRank ? aFirst : bFirst;
	}
}
```

I dont know if it's good solution but works perfect for now.

**Comment by kentcdodds** [comment]
@sdbrannum could you fix this please 😄

**Comment by samyan** [comment]
Main post updated

**Comment by kentcdodds** [comment]
That suggested solution sounds great to me. Would you be willing to implement it?

**Comment by samyan** [comment]
> That suggested solution sounds great to me. Would you be willing to implement it?

I can push **PR** if you want!

**Comment by kentcdodds** [comment]
Please do!

**Comment by samyan** [comment]
> Please do!

Sorry but seems i dont have permissions to PR. I think you need to give me first the collaborator status.

![image](https://user-images.githubusercontent.com/3801362/59422540-d8b58700-8dd0-11e9-9e4d-62182b874e95.png)

**Comment by kentcdodds** [comment]
Maybe this will help: https://kcd.im/pull-request
