### ISSUE TITLE
Add stripDiacritics capabilities

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/match-sorter#8]
Basically [open source](https://kcd.im/write-oss) [this](https://github.com/JedWatson/react-select/blob/master/src/utils/stripDiacritics.js) (cc @JedWatson) and add it as a dependency to match-sorter.

I personally think that this should be enabled by default. Thoughts?

Also, I'm going to work on making it possible to have multiple files right now with our build so we can have dependencies.

**Comment by rogeliog** [comment]
I'm happy to help on this one 😄

**Comment by kentcdodds** [comment]
Actually I've already implemented it, but could you review it for me? #10
