### ISSUE TITLE
Either-Or search

### ISSUE THREAD

**Issue by omakkara** [kentcdodds/match-sorter#81]
Is there a way to search _by_ a list of strings and return items that match at least one of the search strings?

For example:

> const list = ['hi', 'hey', 'hello', 'sup', 'yo']
> matchSorter(list,  'hey' | 'up' | 'plox')

In the above example, I have separated the list of strings with a '|'. I want the the output to contain items that match at least one of the items in this list.

Expected output: ['hey', 'sup']

**Comment by kentcdodds** [comment]
This isn't possible and it's out of scope for the library, but you could do it yourself using something like [`lodash.union`](https://lodash.com/docs/4.17.11#union):

```javascript
const list = ['hi', 'hey', 'hello', 'sup', 'yo']
const matchedValues = _.union(matchSorter(list, 'hey'), matchSorter(list, 'up'), matchSorter(list, 'plox'))
```

That should do it for you. Good luck!
