### ISSUE TITLE
Nested keys not matching others in the array

### ISSUE THREAD

**Issue by skube** [kentcdodds/match-sorter#82]
- `match-sorter` version: 4.0.1
- `node` version: v10.15.3
- `yarn` version: 1.19.0

The example provided in the docs is as follows (and only has one item in each `name` array):

```javascript
const nestedObjList = [
  {name: [{first: 'Janice'}]},
  {name: [{first: 'Fred'}]},
  {name: [{first: 'George'}]},
  {name: [{first: 'Jen'}]},
]
matchSorter(nestedObjList, 'j', {keys: ['name.0.first']})
// [{name: {first: 'Janice'}}, {name: {first: 'Jen'}}]
```

I have a similar structure, however mine only seems to match the first entry in the array.

```javascript
const nestedObjList = [
  {name: [{first: 'Janice', last: 'Smith'}, {first: 'Jon', last: 'Doe'}]},
  {name: [{first: 'Fred', last: 'Astaire'}, {first: 'Jenny', last: 'Doe'}, {first: 'Wilma', last: 'Flintstone'}]},
]
matchSorter(nestedObjList, 'j', {keys: ['name.0.first', 'name.0.last]})
// [{name: {first: 'Janice'}}]
// Where's Jenny?! 🤔
```
Am I doing something wrong?

**Comment by kentcdodds** [comment]
`name.0.first` will allow you to match `Janice` or `Fred` with that data. This is because the `0` in that key string is referencing the first entry in the `name` array of each object.

If you want to match any of the number of arrays, then you should use the property callback. Here's the example from the docs:

```javascript
const list = [{name: 'Janice'}, {name: 'Fred'}, {name: 'George'}, {name: 'Jen'}]
matchSorter(list, 'j', {keys: [item => item.name]})
// [{name: 'Janice'}, {name: 'Jen'}]
```

**Comment by skube** [comment]
Thanks for responding. Your example does work for only one property. I must be dense because I still can't get it work with more complicated structures.

I've created a [sandbox to illustrate](https://codesandbox.io/s/infallible-rosalind-4hvzq)

**Comment by skube** [comment]
A co-worker actually figured it out, so given: 

```js
  const nestedObjList = [
    {
      name: [
       { first: 'Janice', last: 'Smith' },
       { first: 'Jon', last: 'Doe' }
      ],
    },
    {
      name: [
        { first: 'Fred', last: 'Astaire' },
        { first: 'Jenny', last: 'Doe' },
        { first: 'Wilma', last: 'Flintstone' },
      ],
    },
  ];
```

You need to use `map`:

```js
 matchSorter(nestedObjList, 'doe', {
          keys: [
            item => item.name.map(i => i.first),
            item => item.name.map(i => i.last),
          ],
        })
```

@kentcdodds I would recommend updating the docs to make it more clear for this kind of use case. 😃
