### ISSUE TITLE
support regex search?

### ISSUE THREAD

**Issue by ZiyunHe** [kentcdodds/match-sorter#85]
- `match-sorter` version: ^2.2.3

Suggested solution: 

Hi, I fount match-sorter is really useful for my large array. But I really need a regex search. 
Just wonder if there is a way to put regex instead of string. Or if this can be a future feature? 
Thank you.

**Comment by kentcdodds** [comment]
Hi @ZiyunHe,

Sorry, but that's out of scope for this project. I'd recommend you simply do:

```javascript
const matchingItems = yourArray.filter(item => yourRegex.test(item))
```

There's no way for match sorter to rank results of regex. Sorry. Good luck!
