### ISSUE TITLE
Doesn't handle null values

### ISSUE THREAD

**Issue by sbimochan** [kentcdodds/match-sorter#86]
- `match-sorter` version: ^4.0.2
- `node` version: 10.4.0
- `npm` (or `yarn`) version: 6.6

Relevant code or config

```javascript
const nestedObjList = [
  {name: {first: 'Janice'}},
  {name: {first: null}},
  {name: {first: undefined}},
  {name: {first: 'Jen'}},
]
matchSorter(nestedObjList, 'j', {keys: ['name.first']})
```
gives:
Error: ```items.reduce is not a function```
What you did:

I provided null/ undefined values in list

What happened:

![Screen Shot 2019-11-23 at 00 04 38](https://user-images.githubusercontent.com/11685953/69450257-d9d9df80-0d84-11ea-9424-d3d5a82c6089.jpg)

Reproduction repository:

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment]
It looks like you're calling `matchSorter` with a variable called `rows` and I'm guessing that is not an array.

Can you please make a reproduction of your issue?

**Comment by sbimochan** [comment]
Screenshot is from my main problem and above code is example

**Comment by dimaqq** [comment]
Works for me `match-sorter@4.0.2`, babel-compiled, Chrome.

```
  const nestedObjList = [
    {name: {first: "Janice"}},
    {name: {first: null}},
    {name: {first: undefined}},
    {name: {first: "Jen"}},
  ];
  const res = matchSorter(nestedObjList, "j", {keys: ["name.first"]});
  log.info("sorter", res);
```

Finds 2 objects.

**Comment by sbimochan** [comment]
I won't believe it. :P

**Comment by kentcdodds** [comment]
Looks like this is stale, so I'm going to close it. Good luck :)
