### ISSUE TITLE
Option to return matched string

### ISSUE THREAD

**Issue by damianon** [kentcdodds/match-sorter#87]
- `match-sorter` version: 4.0.1
- `node` version: 12.14.1
- `npm`  version: 6.11.3

Relevant code or config

```
type Category = {
    text: string;
    synonyms: string[];
}

 const sorted = matchSorter(
            categories,
            term,
            { keys: ['text', 'synonyms'], threshold: matchSorter.rankings.CONTAINS }
        );
```

What you did:
Search in multiple properties

What happened:
Returned whole matching objects

Problem description:
It's currenty not possible to know which string matched (either text, or one of the synonyms) and one would have to search each object again to find the one that matched.

Suggested solution:
Provide an option to also return the specific matching string. Not sure how this would be possible, as it uses the existing objects type as return type

**Comment by kentcdodds** [comment]
Hi @damianon,

This is definitely something I have considered would be really nice to have, but with the way this library is currently implemented it would take a great deal of effort to do and so I think it's out of scope for this library.

Sorry.

**Comment by Zertz** [comment]
Hi @kentcdodds,

Would you be open to revisiting this? It seems like there could be an option to provide a custom mapping function to replace the [default one](https://github.com/kentcdodds/match-sorter/blob/main/src/index.ts#L95).

**Comment by kentcdodds** [comment]
I'm not certain that will do what you want it to, but feel free to try it and open a PR if you get use out of that.
